/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComedorIndexRouteImport } from './routes/comedor/index'
import { Route as CocinaIndexRouteImport } from './routes/cocina/index'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ComedorMapasRouteImport } from './routes/comedor/mapas'
import { Route as CocinaRecetarioLibroRouteImport } from './routes/cocina/recetario-libro'
import { Route as CocinaRecetarioRouteImport } from './routes/cocina/recetario'
import { Route as CocinaRaInstruccionesRouteImport } from './routes/cocina/ra-instrucciones'
import { Route as BibliotecaRaInstruccionesRouteImport } from './routes/biblioteca/ra-instrucciones'
import { Route as BibliotecaEstanteRouteImport } from './routes/biblioteca/estante'
import { Route as AboutProyectoRouteImport } from './routes/about/proyecto'
import { Route as AboutAutorasRouteImport } from './routes/about/autoras'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ComedorAmigosIndexRouteImport } from './routes/comedor/amigos.index'
import { Route as ComedorAmigosAmigoIdRouteImport } from './routes/comedor/amigos.$amigoId'
import { Route as CocinaRecetaRecetaIdRouteImport } from './routes/cocina/receta.$recetaId'
import { Route as BibliotecaLibroLibroIdRouteImport } from './routes/biblioteca/libro.$libroId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComedorIndexRoute = ComedorIndexRouteImport.update({
  id: '/comedor/',
  path: '/comedor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CocinaIndexRoute = CocinaIndexRouteImport.update({
  id: '/cocina/',
  path: '/cocina/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/biblioteca/',
  path: '/biblioteca/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComedorMapasRoute = ComedorMapasRouteImport.update({
  id: '/comedor/mapas',
  path: '/comedor/mapas',
  getParentRoute: () => rootRouteImport,
} as any)
const CocinaRecetarioLibroRoute = CocinaRecetarioLibroRouteImport.update({
  id: '/cocina/recetario-libro',
  path: '/cocina/recetario-libro',
  getParentRoute: () => rootRouteImport,
} as any)
const CocinaRecetarioRoute = CocinaRecetarioRouteImport.update({
  id: '/cocina/recetario',
  path: '/cocina/recetario',
  getParentRoute: () => rootRouteImport,
} as any)
const CocinaRaInstruccionesRoute = CocinaRaInstruccionesRouteImport.update({
  id: '/cocina/ra-instrucciones',
  path: '/cocina/ra-instrucciones',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRaInstruccionesRoute =
  BibliotecaRaInstruccionesRouteImport.update({
    id: '/biblioteca/ra-instrucciones',
    path: '/biblioteca/ra-instrucciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const BibliotecaEstanteRoute = BibliotecaEstanteRouteImport.update({
  id: '/biblioteca/estante',
  path: '/biblioteca/estante',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutProyectoRoute = AboutProyectoRouteImport.update({
  id: '/about/proyecto',
  path: '/about/proyecto',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAutorasRoute = AboutAutorasRouteImport.update({
  id: '/about/autoras',
  path: '/about/autoras',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComedorAmigosIndexRoute = ComedorAmigosIndexRouteImport.update({
  id: '/comedor/amigos/',
  path: '/comedor/amigos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComedorAmigosAmigoIdRoute = ComedorAmigosAmigoIdRouteImport.update({
  id: '/comedor/amigos/$amigoId',
  path: '/comedor/amigos/$amigoId',
  getParentRoute: () => rootRouteImport,
} as any)
const CocinaRecetaRecetaIdRoute = CocinaRecetaRecetaIdRouteImport.update({
  id: '/cocina/receta/$recetaId',
  path: '/cocina/receta/$recetaId',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaLibroLibroIdRoute = BibliotecaLibroLibroIdRouteImport.update({
  id: '/biblioteca/libro/$libroId',
  path: '/biblioteca/libro/$libroId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/about/autoras': typeof AboutAutorasRoute
  '/about/proyecto': typeof AboutProyectoRoute
  '/biblioteca/estante': typeof BibliotecaEstanteRoute
  '/biblioteca/ra-instrucciones': typeof BibliotecaRaInstruccionesRoute
  '/cocina/ra-instrucciones': typeof CocinaRaInstruccionesRoute
  '/cocina/recetario': typeof CocinaRecetarioRoute
  '/cocina/recetario-libro': typeof CocinaRecetarioLibroRoute
  '/comedor/mapas': typeof ComedorMapasRoute
  '/about/': typeof AboutIndexRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/cocina/': typeof CocinaIndexRoute
  '/comedor/': typeof ComedorIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/biblioteca/libro/$libroId': typeof BibliotecaLibroLibroIdRoute
  '/cocina/receta/$recetaId': typeof CocinaRecetaRecetaIdRoute
  '/comedor/amigos/$amigoId': typeof ComedorAmigosAmigoIdRoute
  '/comedor/amigos/': typeof ComedorAmigosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/about/autoras': typeof AboutAutorasRoute
  '/about/proyecto': typeof AboutProyectoRoute
  '/biblioteca/estante': typeof BibliotecaEstanteRoute
  '/biblioteca/ra-instrucciones': typeof BibliotecaRaInstruccionesRoute
  '/cocina/ra-instrucciones': typeof CocinaRaInstruccionesRoute
  '/cocina/recetario': typeof CocinaRecetarioRoute
  '/cocina/recetario-libro': typeof CocinaRecetarioLibroRoute
  '/comedor/mapas': typeof ComedorMapasRoute
  '/about': typeof AboutIndexRoute
  '/biblioteca': typeof BibliotecaIndexRoute
  '/cocina': typeof CocinaIndexRoute
  '/comedor': typeof ComedorIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/biblioteca/libro/$libroId': typeof BibliotecaLibroLibroIdRoute
  '/cocina/receta/$recetaId': typeof CocinaRecetaRecetaIdRoute
  '/comedor/amigos/$amigoId': typeof ComedorAmigosAmigoIdRoute
  '/comedor/amigos': typeof ComedorAmigosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/about/autoras': typeof AboutAutorasRoute
  '/about/proyecto': typeof AboutProyectoRoute
  '/biblioteca/estante': typeof BibliotecaEstanteRoute
  '/biblioteca/ra-instrucciones': typeof BibliotecaRaInstruccionesRoute
  '/cocina/ra-instrucciones': typeof CocinaRaInstruccionesRoute
  '/cocina/recetario': typeof CocinaRecetarioRoute
  '/cocina/recetario-libro': typeof CocinaRecetarioLibroRoute
  '/comedor/mapas': typeof ComedorMapasRoute
  '/about/': typeof AboutIndexRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/cocina/': typeof CocinaIndexRoute
  '/comedor/': typeof ComedorIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/biblioteca/libro/$libroId': typeof BibliotecaLibroLibroIdRoute
  '/cocina/receta/$recetaId': typeof CocinaRecetaRecetaIdRoute
  '/comedor/amigos/$amigoId': typeof ComedorAmigosAmigoIdRoute
  '/comedor/amigos/': typeof ComedorAmigosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/about/autoras'
    | '/about/proyecto'
    | '/biblioteca/estante'
    | '/biblioteca/ra-instrucciones'
    | '/cocina/ra-instrucciones'
    | '/cocina/recetario'
    | '/cocina/recetario-libro'
    | '/comedor/mapas'
    | '/about/'
    | '/biblioteca/'
    | '/cocina/'
    | '/comedor/'
    | '/.mcp/invoke-tool/$tool'
    | '/biblioteca/libro/$libroId'
    | '/cocina/receta/$recetaId'
    | '/comedor/amigos/$amigoId'
    | '/comedor/amigos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/about/autoras'
    | '/about/proyecto'
    | '/biblioteca/estante'
    | '/biblioteca/ra-instrucciones'
    | '/cocina/ra-instrucciones'
    | '/cocina/recetario'
    | '/cocina/recetario-libro'
    | '/comedor/mapas'
    | '/about'
    | '/biblioteca'
    | '/cocina'
    | '/comedor'
    | '/.mcp/invoke-tool/$tool'
    | '/biblioteca/libro/$libroId'
    | '/cocina/receta/$recetaId'
    | '/comedor/amigos/$amigoId'
    | '/comedor/amigos'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/about/autoras'
    | '/about/proyecto'
    | '/biblioteca/estante'
    | '/biblioteca/ra-instrucciones'
    | '/cocina/ra-instrucciones'
    | '/cocina/recetario'
    | '/cocina/recetario-libro'
    | '/comedor/mapas'
    | '/about/'
    | '/biblioteca/'
    | '/cocina/'
    | '/comedor/'
    | '/.mcp/invoke-tool/$tool'
    | '/biblioteca/libro/$libroId'
    | '/cocina/receta/$recetaId'
    | '/comedor/amigos/$amigoId'
    | '/comedor/amigos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AboutAutorasRoute: typeof AboutAutorasRoute
  AboutProyectoRoute: typeof AboutProyectoRoute
  BibliotecaEstanteRoute: typeof BibliotecaEstanteRoute
  BibliotecaRaInstruccionesRoute: typeof BibliotecaRaInstruccionesRoute
  CocinaRaInstruccionesRoute: typeof CocinaRaInstruccionesRoute
  CocinaRecetarioRoute: typeof CocinaRecetarioRoute
  CocinaRecetarioLibroRoute: typeof CocinaRecetarioLibroRoute
  ComedorMapasRoute: typeof ComedorMapasRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
  CocinaIndexRoute: typeof CocinaIndexRoute
  ComedorIndexRoute: typeof ComedorIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  BibliotecaLibroLibroIdRoute: typeof BibliotecaLibroLibroIdRoute
  CocinaRecetaRecetaIdRoute: typeof CocinaRecetaRecetaIdRoute
  ComedorAmigosAmigoIdRoute: typeof ComedorAmigosAmigoIdRoute
  ComedorAmigosIndexRoute: typeof ComedorAmigosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comedor/': {
      id: '/comedor/'
      path: '/comedor'
      fullPath: '/comedor/'
      preLoaderRoute: typeof ComedorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocina/': {
      id: '/cocina/'
      path: '/cocina'
      fullPath: '/cocina/'
      preLoaderRoute: typeof CocinaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/biblioteca'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comedor/mapas': {
      id: '/comedor/mapas'
      path: '/comedor/mapas'
      fullPath: '/comedor/mapas'
      preLoaderRoute: typeof ComedorMapasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocina/recetario-libro': {
      id: '/cocina/recetario-libro'
      path: '/cocina/recetario-libro'
      fullPath: '/cocina/recetario-libro'
      preLoaderRoute: typeof CocinaRecetarioLibroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocina/recetario': {
      id: '/cocina/recetario'
      path: '/cocina/recetario'
      fullPath: '/cocina/recetario'
      preLoaderRoute: typeof CocinaRecetarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocina/ra-instrucciones': {
      id: '/cocina/ra-instrucciones'
      path: '/cocina/ra-instrucciones'
      fullPath: '/cocina/ra-instrucciones'
      preLoaderRoute: typeof CocinaRaInstruccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/ra-instrucciones': {
      id: '/biblioteca/ra-instrucciones'
      path: '/biblioteca/ra-instrucciones'
      fullPath: '/biblioteca/ra-instrucciones'
      preLoaderRoute: typeof BibliotecaRaInstruccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/estante': {
      id: '/biblioteca/estante'
      path: '/biblioteca/estante'
      fullPath: '/biblioteca/estante'
      preLoaderRoute: typeof BibliotecaEstanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/proyecto': {
      id: '/about/proyecto'
      path: '/about/proyecto'
      fullPath: '/about/proyecto'
      preLoaderRoute: typeof AboutProyectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/autoras': {
      id: '/about/autoras'
      path: '/about/autoras'
      fullPath: '/about/autoras'
      preLoaderRoute: typeof AboutAutorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comedor/amigos/': {
      id: '/comedor/amigos/'
      path: '/comedor/amigos'
      fullPath: '/comedor/amigos/'
      preLoaderRoute: typeof ComedorAmigosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comedor/amigos/$amigoId': {
      id: '/comedor/amigos/$amigoId'
      path: '/comedor/amigos/$amigoId'
      fullPath: '/comedor/amigos/$amigoId'
      preLoaderRoute: typeof ComedorAmigosAmigoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocina/receta/$recetaId': {
      id: '/cocina/receta/$recetaId'
      path: '/cocina/receta/$recetaId'
      fullPath: '/cocina/receta/$recetaId'
      preLoaderRoute: typeof CocinaRecetaRecetaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/libro/$libroId': {
      id: '/biblioteca/libro/$libroId'
      path: '/biblioteca/libro/$libroId'
      fullPath: '/biblioteca/libro/$libroId'
      preLoaderRoute: typeof BibliotecaLibroLibroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AboutAutorasRoute: AboutAutorasRoute,
  AboutProyectoRoute: AboutProyectoRoute,
  BibliotecaEstanteRoute: BibliotecaEstanteRoute,
  BibliotecaRaInstruccionesRoute: BibliotecaRaInstruccionesRoute,
  CocinaRaInstruccionesRoute: CocinaRaInstruccionesRoute,
  CocinaRecetarioRoute: CocinaRecetarioRoute,
  CocinaRecetarioLibroRoute: CocinaRecetarioLibroRoute,
  ComedorMapasRoute: ComedorMapasRoute,
  AboutIndexRoute: AboutIndexRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
  CocinaIndexRoute: CocinaIndexRoute,
  ComedorIndexRoute: ComedorIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  BibliotecaLibroLibroIdRoute: BibliotecaLibroLibroIdRoute,
  CocinaRecetaRecetaIdRoute: CocinaRecetaRecetaIdRoute,
  ComedorAmigosAmigoIdRoute: ComedorAmigosAmigoIdRoute,
  ComedorAmigosIndexRoute: ComedorAmigosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
